[package]
name = "sierra_launcher"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = "0.14.0"
iced_layershell = "0.14.2"
notify = "6.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8.13"